### ISSUE TITLE
Debezium avro encoded kafka msg Invalid Java object for schema 

### ISSUE THREAD

**Issue by ShahNewazKhan** [aiven/gcs-connector-for-apache-kafka#189] opened 2022-07-11 02:49 UTC
I have a kafka topic with `avro` serialized cdc messages produced by the debezium pg source connector and am getting the following error:

```
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema "org.apache.kafka.connect.data.Timestamp" with type INT64: class java.lang.Long
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)
```

For a message with the following avro schema:

```
{
              "name": "<COLUMN_NAME>",
              "type": [
                "null",
                {
                  "type": "long",
                  "connect.version": 1,
                  "connect.name": "org.apache.kafka.connect.data.Timestamp",
                  "logicalType": "timestamp-millis"
                }
              ],
              "default": null
            }
```

Looking into it looks like an issue similar to https://github.com/confluentinc/schema-registry/issues/1604

The code block triggering this is https://github.com/apache/kafka/blob/f0282498e7a312a977acb127557520def338d45c/connect/api/src/main/java/org/apache/kafka/connect/data/ConnectSchema.java#L239

**Comment by ivanyu** [comment] 2022-07-11 05:34
Hi @ShahNewazKhan 
Thanks for this report. In the ticket you point to, I propose to use `target.type` = `Date`. Will it help in your case or I misunderstood something?

**Comment by ShahNewazKhan** [comment] 2022-07-11 15:30
Hi @ivanyu, thanks for looking into this, the [SMT](https://github.com/aiven/s3-connector-for-apache-kafka/issues/92) work arround will not help in our case because we would need to account for a SMT for every `timestamp-millis` column in our database. 

We are using Avro serialization on the Debezium source connector to account for schema evolution so it is not feasible for us to serialise the Debezium messages to JSON or JSONL. 


I am including the full stacK trace of the issue trying to read from a `Debezium Avro` encoded topic:

```
Error converting message value in topic '<TOPIC_NAME>' partition 5 at offset 0 and timestamp 1657377816061: Invalid default value (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value
at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1564)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1469)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1445)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1469)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1445)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1323)
at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1047)
at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:92)
at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:560)
at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1445)
at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1323)
at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1047)
at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:92)
at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:560)
at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema "org.apache.kafka.connect.data.Timestamp" with type INT64: class java.lang.Long
at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)
```

**Comment by ivanyu** [comment] 2022-07-12 07:10
You don't have a pre-defined set of fields that needs conversion and when a field like this appears, the pipeline breaks until a new SMT is added to handle it. Do I understand this right?

**Comment by ShahNewazKhan** [comment] 2022-07-12 07:13
> You don't have a pre-defined set of fields that needs conversion and when a field like this appears, the pipeline breaks until a new SMT is added to handle it. Do I understand this right?

Hi Ivan, yes that is correct.

**Comment by ivanyu** [comment] 2022-07-12 09:44
Having checked the stacktrace again, it seems the issue is not in the connector and the transformations won't help either because the error happens before the transformations could be applied. Somethings is wrong with the data.

**Comment by ShahNewazKhan** [comment] 2022-07-12 18:57
> Having checked the stacktrace again, it seems the issue is not in the connector and the transformations won't help either because the error happens before the transformations could be applied. Somethings is wrong with the data.

Interesting, can you help me understand how I can debug the issue with the data in the topic, some further context, we can ingest the Avro data from this topic into BigQuery using the [bq kakfa connect sink](https://github.com/confluentinc/kafka-connect-bigquery)

**Comment by ivanyu** [comment] 2022-07-14 11:45
Can you consume these data (let's say concretely this particular topic-partition and offset 0) with Avro deserialization? 
Assuming this is all in Aiven, could you please ping us through the support, we could look into the issue together

**Comment by ShahNewazKhan** [comment] 2022-07-21 03:48
Hi Ivan, sorry about the delayed response, I was able to deserialize the Avro topic msg manually. 

We are running a `debezium source connector` that produces the Avro messages to the Aiven Kafka Topics and using the Aiven GCS sink connector to read from it however running into the the `timestamp-millis` issue as describe in https://github.com/aiven/gcs-connector-for-apache-kafka/issues/189#issuecomment-1180556838.

Adding comment here as I don't get notification when the Aiven Support Chat is updated.

**Comment by ThomasDangleterre** [comment] 2022-09-12 13:19
Hello, 

I faced the same issue : 

```java
Caused by: org.apache.kafka.connect.errors.SchemaBuilderException: Invalid default value
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:131)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1564)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1445)
	at io.confluent.connect.avro.AvroData.toConnectSchema(AvroData.java:1323)
	at io.confluent.connect.avro.AvroData.toConnectData(AvroData.java:1047)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:92)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:540)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:496)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	... 13 more
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema "io.confluent.connect.avro.Union" with type STRUCT: class java.lang.String
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)
	at org.apache.kafka.connect.data.SchemaBuilder.defaultValue(SchemaBuilder.java:129)
	... 23 more
```
The error occurred on a splunk connector but I suspect version of avro libraries of the gcs plugin to be too ld (confluent platform 4.14) for my other connectors ( confluent platform > 7.0.0).

I removed the gcs connector in order to make other plugin works. 

Have you planned upgrading Confluent platform to at least 7.0.X ?

**Comment by ivanyu** [comment] 2022-09-13 10:07
Thanks @ThomasDangleterre. We should remove these JARs altogether from the distribution. Normally, they should be provided by the Connect installation, not as a part of a connector.

**Comment by jeqo** [comment] 2023-06-21 14:07
@ShahNewazKhan @ThomasDangleterre there has been some changes on the dependencies: https://github.com/aiven/commons-for-apache-kafka-connect/pull/166
Though, our assessment is that this issue should not happen if the plugin is not placed on the same classpath as the connect binaries. 
Let us know if this agrees with your experience to close this issue.
Cheers!

**Comment by jeqo** [comment] 2023-06-29 08:41
Will close this one as it seems to be caused by a plugin deployment issue leading to classpath conflict. If this ends up not being the case, please reopen this issue. Thanks!

**Closed by jeqo** 2023-06-29 08:41 UTC
